pipeline:
  Python test:
    image: python:3
    commands:
      - apt-get -qq update
      - apt-get -qq install libjpeg-dev zlib1g-dev gcc
      - pip install -q --upgrade pip
      - pip install -qUr requirements.txt
      - rm -f movit/settings_local.py
      - cp movit/settings_local.py.tpl movit/settings_local.py
      - python3 manage.py test
